# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Intermediate_01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Intermediate_01
  pod 'Firebase/Auth'

end
